spring:
  thymeleaf:
    cache: false

  datasource:
    generate-unique-name: false
    name: tacocloud
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 7421Crackers
    url: jdbc:postgresql://192.168.1.65:5432/tacocloud_test

  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true